FUNC LABEL 0
    CAL VAL 1
    CAL VAL 2
    CAL VAL 3
    CAL VAL 4
    RET
FUNC LABEL 7
    MOV REG 2 VAL 1
    NOT REG 1
    ADD REG 1 REG 2
    ADD REG 0 REG 1
    EQU REG 0
    PRINT REG 0
    RET
FUNC LABEL 4
    MOV STK 1 VAL 42
    REF STK 2 STK 1
    REF PTR 2 PTR 2
    REF STK 3 STK 1
    MOV REG 0 STK 1
    MOV REG 1 STK 3
    CAL VAL 7
    RET
FUNC LABEL 3
    MOV STK 1 VAL 19
    REF STK 2 STK 1
    REF PTR 2 STK 2
    REF STK 2 STK 2
    MOV REG 0 STK 1
    MOV REG 1 STK 2
    CAL VAL 7
    RET
FUNC LABEL 2
    MOV STK 1 VAL 5
    REF STK 2 STK 1
    REF STK 3 PTR 2
    MOV REG 0 STK 3
    MOV REG 1 STK 2
    CAL VAL 7
    RET
FUNC LABEL 1
    MOV STK 1 VAL 7
    REF STK 2 STK 1
    REF STK 3 STK 1
    MOV REG 0 STK 2
    MOV REG 1 STK 3
    CAL VAL 7
    RET
